[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
solc_version = '0.8.25'
libs = ['node_modules', 'lib']
optimizer_runs = 10_000

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000

[rpc_endpoints]
arbitrum = "https://arbitrum-one-rpc.publicnode.com"
avalanche = "https://avalanche-c-chain-rpc.publicnode.com"
base = "https://mainnet.base.org"
bnb_smart_chain = "https://bsc-dataseed.binance.org"
gnosis_chain = "https://rpc.gnosischain.com"
localhost = "http://localhost:8545"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
optimism = "https://optimism-rpc.publicnode.com"
polygon = "https://polygon-bor-rpc.publicnode.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
superseed = "https://rpc-superseed-mainnet-0.t.conduit.xyz/${API_KEY_CONDUIT}"
superseed_sepolia = "https://rpc-sepolia-superseed-826s35710w.t.conduit.xyz/${API_KEY_CONDUIT}"

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }
sepolia = { key = "${API_KEY_ETHERSCAN}" }